name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "${{ secrets.GITEE_USERNAME }}"
          git config --global user.email "you@example.com"

      - name: Push to Gitee (Forced)
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PAT: ${{ secrets.GITEE_PAT }}
        run: |
          git remote add gitee https://${GITEE_USERNAME}:${GITEE_PAT}@gitee.com/terrafirma/MAKCM_v2_files.git
          git push --force --all gitee
          git push --force --tags gitee
